vision_encoder:
 type: multi
 args:
  dim: 64
  num_heads: 4
  num_layers: 6
  num_channels: 4

text_decoder:
 type: cross
 args:
  dim: 64
  num_layers: 12
  num_heads: 4
  vocab_dim: 64
  max_saml_layers: 230

optimizer:
 type: adamw
 args:
  lr: 1e-4
  weight_decay: 1e-2

hyperparameters:
 epochs: 10000
 max_patience: 1000
 batch_size: 64
 train_split_size: 0.8
 seed: 69
 test_data: ./output/test/