vision_encoder:
 type: vit
 args:
  dim: 512
  num_heads: 8
  num_layers: 6
  image_size: 384
  patch_size: 16
  num_channels: 4

text_encoder:
 type: saml
 args:
  dim: 512
  num_heads: 8
  num_layers: 6
  vocab_dim: 128
  max_saml_layers: 230

clip_trainer:
  final_dim: 1024
  
optimizer:
 type: adamw
 args:
  lr: 1e-5
  weight_decay: 1e-2

hyperparameters:
 epochs: 10000
 max_patience: 20
 batch_size: 128
 train_split_size: 0.8
 seed: 69