vision_encoder:
 type: multi
 args:
  dim: 128
  num_heads: 4
  num_layers: 3
  num_channels: 4

text_encoder:
 type: saml
 args:
  dim: 128
  num_heads: 4
  num_layers: 6
  vocab_dim: 64
  max_saml_layers: 230

clip_trainer:
  final_dim: 256
  
optimizer:
 type: adamw
 args:
  lr: 1e-5
  weight_decay: 1e-2

hyperparameters:
 epochs: 10000
 max_patience: 50
 batch_size: 64
 train_split_size: 0.8
 seed: 69